# Generated by Django 5.0.2 on 2024-03-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nlevel', models.CharField(blank=True, max_length=1, null=True)),
                ('review', models.BooleanField(blank=True, null=True)),
                ('pricebook', models.TextField(blank=True, null=True)),
                ('datepublic', models.DateField(blank=True, null=True)),
                ('datesell', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
